server:
  port: 8082
  servlet:
    context-path: /accounting

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/realms/spring-cloud-config-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8081/auth/realms/spring-cloud-config-realm

keycloak:
  realm: tutor-microservices-realm
  auth-server-url: http://localhost:8081/auth
  resource: accounting-service
  client-id: accounting_service-client
  credentials:
    secret: duKYfSGYqW2mO94HMxQVtfIfPonUQmbR
    use-resource-role-mappings: true
    bearer-only: true