spring:
  cloud:
    gateway:
      routes:
        - id: accounting-service
          uri: lb://accounting-service
          predicates:
            - Path=/accounting/**
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders:
                - "*"
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courseapi/**
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders:
                - "*"
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders:
                - "*"
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        # SockJS route
        - id: signal-service-sockjs-route
          uri: lb://signal-service
          predicates:
            - Path=/signaling/info/**
        # Normal Websocket route
        - id: signal-service
          uri: lb:ws://signal-service
          predicates:
            - Path=/signaling/**
        - id: livechat-service
          uri: lb://livechat-service
          predicates:
            - Path=/livechat/**
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders:
                - "*"

