spring:
  cloud:
    gateway:
      routes:
        - id: accounting-service
          uri: lb://accounting-service
          predicates:
            - Path=/accounting/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
              - Path=/payment/**
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

