server:
  port: 8082
  servlet:
    context-path: /accounting

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutor-system
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  application:
    name: accounting-service
#keycloak:
#  realm: tutor-microservices-realm
#  auth-server-url: http://localhost:8081
#  resource: accounting-service
#  client-id: accounting_service-client
#  admin-client-id: admin-cli
#  credentials:
#    secret: duKYfSGYqW2mO94HMxQVtfIfPonUQmbR
#    use-resource-role-mappings: true
#    bearer-only: true