spring:
  cloud:
    config:
      allow-override: true
      override-none: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRAP_ROOT_VALUE: true
      AUTO_DETECT_FIELDS: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
