spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutor-system
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

payment:
  vnpay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmn-code: FZ3V3X6E
    secret-key: GCSR4PD9XIQ4YKRJC3XY8FZM00VX8IFP
    return-url: http://localhost:8084/payment/integration/vn-pay-callback
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    version: 2.1.0
    command: pay
    order-type: other

server:
  port: 0
  servlet:
    context-path: /payment