spring:
  cloud:
    config:
      allow-override: true
      override-none: true
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            authorization-grant-type: authorization_code
#            client-id: ${keycloak.client-id}
#            client-secret: ${keycloak.credentials.secret}
#            redirect-uri: '{baseUrl}/authorized/{registrationId}'
#        provider:
#          keycloak:
#            authorization-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
#            token-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token

  jackson:
    property-naming-strategy: SNAKE_CASE
webclient:
  base-url: 'http://localhost:8082/accounting'
  connect-timeout-ms: 10000
  read-timeout-ms: 10000
  write-timeout-ms: 10000
  max-in-memory-size: 10485760 # 10MB
  content-type: 'application/json'
  accept-type: 'application/json'
security:
  default-client-registration-id: keycloak
