spring:
  cloud:
    config:
      allow-override: true
      override-none: true
  openfeign:
    oauth2:
      enabled: true
      clientRegistrationId: keycloak
  jackson:
    property-naming-strategy: SNAKE_CASE
