spring:
  cloud:
    config:
      allow-override: true
      override-none: true
  jackson:
    property-naming-strategy: SNAKE_CASE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
